<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "stage".
 *
 * @property int $id
 * @property int $month_id
 * @property int $start_date
 * @property int $end_date
 * @property int $places_beads
 * @property int $places_lavender
 * @property int $price
 * @property int $publish
 * @property int $deleted
 *
 * @property Booking[] $bookings
 * @property Month $month
 */
class Stage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'stage';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['month_id'], 'required'],
            [['start_date', 'end_date',], 'safe'],
            [['month_id', 'places_beads', 'places_lavender', 'price', 'publish', 'deleted'], 'integer'],
            [['month_id'], 'exist', 'skipOnError' => true, 'targetClass' => Month::className(), 'targetAttribute' => ['month_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'month_id' => 'Month ID',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'places_beads' => 'Places Beads',
            'places_lavender' => 'Places Lavender',
            'price' => 'Price',
            'publish' => 'Publish',
            'deleted' => 'Deleted',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookings()
    {
        return $this->hasMany(Booking::className(), ['stage_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonth()
    {
        return $this->hasOne(Month::className(), ['id' => 'month_id']);
    }
    public function beforeSave($insert)
    {
        if ($this->start_date){

            $this->start_date =
                is_string($this->start_date)
                    ? strtotime($this->start_date)
                    : $this->start_date;
        }
        if ($this->end_date){

            $this->end_date =
                is_string($this->end_date)
                    ? strtotime($this->end_date)
                    : $this->end_date;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
