<?php

namespace common\models;

use common\behaviors\ImgUploadBehavior;
use Yii;

/**
 * This is the model class for table "month".
 *
 * @property int $id
 * @property int $tour_id
 * @property string $start
 * @property string $end
 * @property int $publish
 * @property string $image
 *
 * @property Accom[] $accoms
 * @property Tour $tour
 * @property Stage[] $stages
 */
class TourPeriod extends \yii\db\ActiveRecord
{
    public $maxCount;

    public function afterFind()
    {
        $this->maxCount = $this->tour->max_count;
        parent::afterFind();
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tour_periods';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tour_id'], 'required'],
            [['tour_id', 'publish'], 'integer'],
            [['start','end'], 'date','format' => 'yyyy-MM-dd'],
            [['start','end'], 'required'],
            [['tour_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tour::className(), 'targetAttribute' => ['tour_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tour_id' => 'Тур',
            'start' => 'Начало периода',
            'end' => 'Завершение периода',
            'publish' => 'Публикация',
        ];
    }

    public function behaviors()
    {
        return [
            'ImgUploadBehavior' => [
                'class' => ImgUploadBehavior::className(),
                'noImage' => 'no_image.png',
                'folder' => '/uploads/images/tour_periods',
                'propImage' => 'image',
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccoms()
    {
        return $this->hasMany(Accom::className(), ['id' => 'tour_id'])->viaTable('tour_accom',['accom_id','id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTour()
    {
        return $this->hasOne(Tour::className(), ['id' => 'tour_id']);
    }

    public function beforeSave($insert)
    {
        /*
        if ($this->title){

            $this->title =
                is_string($this->title)
                    ? strtotime('01.'.$this->title)
                    : $this->title;
        }else{
            $this->title = time();
        }
        */
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
